sonar.projectKey=Sam-rst_YamMaster
sonar.organization=sam-rst

sonar.sources=backend/src,frontend
sonar.tests=backend/src/**/__tests__,frontend/**/__tests__
sonar.test.inclusions=**/*.test.ts,**/*.test.js,**/*.spec.ts,**/*.spec.js

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/.expo/**,**/prisma/migrations/**
